cats_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]

end

cats_99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'date'
require 'action_view'
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    COLORS = %w(white black grey brown orange calico)
    validates :sex, inclusion: {in: %w(m f), message: "%(value) is not a valid sex" }
    validates :color, inclusion: {in: COLORS, message: "%cats aren't (value)" }

    has_many :cat_rental_requests,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

    def self.colors
        COLORS 
    end

    def age
        # date_now = DateTime.now.to_date
        # date_now.year - @birth_date.year 
        time_ago_in_words(birth_date)
    end


end

cats_99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#

class CatRentalRequest < ApplicationRecord
    STATUSES = ['PENDING', 'APPROVED', 'DENIED']
    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: {in: STATUSES, message: "%illegal status" }

    belongs_to :cat,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :Cat
end

cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all

        render :index
    end
    
    def show
        @cat = Cat.find(params[:id])
        if @cat
            render :show
        else
            redirect_to cats_url
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        cat = Cat.new(cat_params)
        if cat.save
            redirect_to cat_url(cat)
        else
            render json: cat.errors.full_messages, status: :unprocessable_entity
        end
    end

    def edit
        @cat = Cat.find(params[:id])
        
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])
        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render json: cat.errors.full_messages, status: :unprocessable_entity
        end
    end

    private
    def cat_params
        params.require(:cat).permit(:name, :sex, :color, :description, :birth_date)
    end
end

cats_99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_99/app/views/cats/_form.html.erb
 <% action = cat.persisted? ? cat_url(cat) : cats_url %>
 <% button_text = cat.persisted? ? "Edit The Cat" : "Make The Cat" %>

<form action="<%=action%>" method="post">
<% if cat.persisted?%>
    <input type="hidden" name="_method" value="PATCH">
<%end%>

    <p><label for="cat_name">Name</label>
    <input id="cat_name" type="text" name="cat[name]" value = "<%= cat.name %>"></p>

    <p><label for="cat_sex">Sex</label>

    <input id="cat_sex" type="radio" name="cat[sex]" value='m' <%= cat.sex == "m" ? "checked" : ""  %> > M
    <input id="cat_sex" type="radio" name="cat[sex]" value='f' <%= cat.sex == "f" ? "checked" : ""  %> > F
    </p> 

    <p><label for="cat_color">Color</label>
    <select name="cat[color]" >
        <option disabled selected> <%= cat.color %> </option>
        <% Cat.colors.each do |color| %>
            <option value = "<%= color %>"  > <%= color %> </option>
        <% end %>
    </select></p>

    <p><label for="birthday">Birth Date</label>
    <input type="date" id="birthday" name="cat[birth_date]"
            value = "<%= cat.birth_date %>"
            min="0000-01-01" max="2019-12-31">
    </p>

    <p><label for="description">Describe The Cat</label>
    <input type="textarea" id="description" name="cat[description]" value = "<%= cat.description %>">
    </p>
    
    <input type="submit" value="<%=button_text %>">
</form>

cats_99/app/views/cats/edit.html.erb
<h1>Edit The Cat</h1>

<%= render 'form', cat: @cat %>

cats_99/app/views/cats/index.html.erb
<h1>This the Index</h1>
<% @cats.each do |cat| %>
    <%= cat.name + " | " + cat.color + " | " + cat.description %>
    <a href="<%= cat_url(cat) %>">Show cat</a>
    <a href="<%= edit_cat_url(cat) %>">Edit cat</a>
    <br/>
<% end %>

cats_99/app/views/cats/new.html.erb
<h1>This Is a New Cat</h1>

<%= render 'form', cat: @cat %>

cats_99/app/views/cats/show.html.erb
<h1>This is a Cat</h1>
<p><%= @cat.name %></p>
<p><%= @cat.color %></p>
<p><%= @cat.description %></p>
<p><%= @cat.birth_date %></p>
<p><%= @cat.age %></p>
<p><%= @cat.sex %></p>

cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>